dev:
  api:
    Resources:
  jobs:
    Resources:

prd:
  api:
    Resources:
      TimeLogsMetric:
        Type: AWS::Logs::MetricFilter
        Properties:
          FilterPattern: "error"
          LogGroupName: /aws/lambda/${self:service}-${self:provider.stage}-handler
          MetricTransformations:
            - MetricName: "[Handler] Too many errors test"
              MetricValue: 1
              MetricNamespace: tests-alerts

      HandlerTooManyErrorLogs:
        Type: AWS::CloudWatch::Alarm
        Properties:
          AlarmName: "[Testes] ${self:service}-${self:provider.stage}-handler"
          ComparisonOperator: GreaterThanThreshold
          Period: 300 # 5 min
          Threshold: 1
          EvaluationPeriods: 1
          Statistic: Sum
          TreatMissingData: notBreaching
          Metrics:
            - Id: m1
              MetricStat:
                Metric:
                  Namespace: tests-alerts
                  MetricName: "[Handler] Too many errors test"
                  # Dimensions:
                  #   - Name: YourDimensionName
                  #     Value: YourDimensionValue
                Period: 60
                Stat: SampleCount
              ReturnData: true
          # ExtendedStatistic: "IF(HOUR(m1) > 9 AND HOUR(m1) < 17, m1)"

  jobs:
    Resources:
