service: aws-test
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  stage: ${opt:stage, 'prd'}

functions:
  handler:
    handler: index.handler
    events:
      - httpApi:
          method: post
          path: /

resources:
  - ${file(alerts.yml):${self:provider.stage}.api}
